/* 
 * Bundle Server API
 *
 * This API enables users to download packed bundles from the bundle server.
 *
 * OpenAPI spec version: 0.0.0
 * Contact: bruluk5w@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using System;
using RestSharp;

namespace IO.Swagger.Client
{
    /// <summary>
    /// A delegate to ExceptionFactory method
    /// </summary>
    /// <param name="methodName">Method name</param>
    /// <param name="response">Response</param>
    /// <returns>Exceptions</returns>    
    public delegate Exception ExceptionFactory(string methodName, IRestResponse response);
}
