/* 
 * Bundle Server API
 *
 * This API enables users to download packed bundles from the bundle server.
 *
 * OpenAPI spec version: 0.0.0
 * Contact: bruluk5w@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BundleDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BundleDetailsTests
    {
        // TODO uncomment below to declare an instance variable for BundleDetails
        //private BundleDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BundleDetails
            //instance = new BundleDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BundleDetails
        /// </summary>
        [Test]
        public void BundleDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BundleDetails
            //Assert.IsInstanceOfType<BundleDetails> (instance, "variable 'instance' is a BundleDetails");
        }

        /// <summary>
        /// Test the property 'UniqueId'
        /// </summary>
        [Test]
        public void UniqueIdTest()
        {
            // TODO unit test for the property 'UniqueId'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Test]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Engines'
        /// </summary>
        [Test]
        public void EnginesTest()
        {
            // TODO unit test for the property 'Engines'
        }
        /// <summary>
        /// Test the property 'Platforms'
        /// </summary>
        [Test]
        public void PlatformsTest()
        {
            // TODO unit test for the property 'Platforms'
        }

    }

}
